version: "3.9"
services:

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_db=rali
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "5432:5432"

  api:
    container_name: rali
    build: .
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DEV_USER: postgres
      DEV_PASSWORD: postgres
      DEV_DB: rali
      DEV_HOST: postgres
      TEST_USER: postgres
      TEST_PASSWORD: postgres
      TEST_DB: rali_test
      TEST_HOST: postgres
    volumes:
      - ./:/app
    depends_on:
      - postgres