const LIGHTWEIGHT = 'lightweight'
const MIDDLEWEIGHT = 'middleweight'
const CRUISERWEIGHT = 'cruiserweight'
const HEAVYWEIGHT = 'heavyweight'

const LIGHTWEIGHTLIMIT = 200
const MIDDLEWEIGHTLIMIT = 300
const CRUISERWEIGHTLIMIT = 400
const HEAVYWEIGHTLIMIT = 500

module.exports = {
    LIGHTWEIGHT,
    MIDDLEWEIGHT,
    CRUISERWEIGHT,
    HEAVYWEIGHT,
    LIGHTWEIGHTLIMIT,
    MIDDLEWEIGHTLIMIT,
    CRUISERWEIGHTLIMIT,
    HEAVYWEIGHTLIMIT,
    WEIGHT_CLASS: [ LIGHTWEIGHT, MIDDLEWEIGHT, CRUISERWEIGHT, HEAVYWEIGHT ],
}